### PR TITLE
Fix for issue #1903 (Krøyer_PS.y4m desync)

### LINKED ISSUE #1903: Decoding error on encoded Krøyer_PS.y4m from subset1 at high quantizers
The command line options are `--tiles 4 --quantizer [252|220]`, everything else is default. Lower quantizer values (among the default quantizers tested on AWCY) do not seem to generate corrupted bitstreams. I have not tested much besides that.

dav1d output:
```
dav1d 0.4.0-47-g556890b - by VideoLAN
Error decoding frame: Invalid argument
No data decoded
```

aomdec output:
```
Warning: Failed to decode frame 1: Corrupt frame detected
Warning: Additional information: Corrupted segment_ids
```

### PR DESCRIPTION
**Pull request by xiphmont**
Tiling had broken an edge-of-frame check in superblock queue flush triggering.  It was checking tile-local superblock offset against the edge of the frame instead of checking *global* superblock offset against the edge of frame.  This should fix the desync bug with no other functional change.

Fixes #1903

### CODE REVIEW

File: src/tiling/tile_restoration_state.rs [hunk 1]
```diff
@@ -225,18 +225,21 @@ macro_rules! tile_restoration_plane_common {
       pub fn restoration_unit_last_sb_for_rdo<T: Pixel>(
         &self,
         fi: &FrameInvariants<T>,
-        sbo: TileSuperBlockOffset,
+        global_sbo: PlaneSuperBlockOffset,
```
Comment (ycho) [inline src/tiling/tile_restoration_state.rs]: Does 'global' mean the sbo in the frame, instead of the tile, correct?

**Comment by barrbrain** [comment]
I confirmed that this fixes #1903. Minor comment on commit subject: #1903 is an issue rather than a pull request, so the PR prefix is misleading. Also, including "Fixes #1903." in the body will enable GItHub to auto-close the issue.

File: src/tiling/tile_restoration_state.rs (hunk 1 above)
Comment (xiphmont) [reply src/tiling/tile_restoration_state.rs]: yes.

**Comment by xiphmont** [comment]
> Looks good, does awcy agree?

Yes, all zeroes (as expected, default AWCY didn't trip the bug).

File: src/tiling/tile_restoration_state.rs (hunk 1 above)
Comment (tmatth) [reply src/tiling/tile_restoration_state.rs]: I might have called it `frame_sbo` but not really a dealbreaker

**Comment by xiphmont** [comment]
We use 'Frames' in several places that are not the viewable frame....

Monty

**Comment by xiphmont** [comment]
....but sure, it's certainly no worse, might be better.

File: src/tiling/tile_restoration_state.rs (hunk 1 above)
Comment (ycho) [reply src/tiling/tile_restoration_state.rs]: > I might have called it `frame_sbo` but not really a dealbreaker

Yes, we will write a patch to rename it when monty is back to seep.... *_*
