### PR TITLE
config: constrain max fps

### LINKED ISSUE #3216: Crash on encode fuzztest
**Describe the bug**
I discovered this crash on fuzz testing encode:

```

Failing input:

	fuzz/artifacts/encode/crash-6c4a10dc08c47e5e5e818287d7dc742b58548506

Output of `std::fmt::Debug`:

	ArbitraryEncoder {
	    config: Config {
	        enc: EncoderConfig {
	            width: 247,
	            height: 80,
	            sample_aspect_ratio: Rational {
	                num: 5714872554696429391,
	                den: 5714874072313712463,
	            },
	            time_base: Rational {
	                num: 8448,
	                den: 620756992,
	            },
	            bit_depth: 8,
	            chroma_sampling: Cs420,
	            chroma_sample_position: Unknown,
	            pixel_range: Limited,
	            color_description: None,
	            mastering_display: None,
	            content_light: None,
	            level_idx: Some(
	                31,
	            ),
	            enable_timing_info: false,
	            still_picture: true,
	            error_resilient: false,
	            switch_frame_interval: 0,
	            min_key_frame_interval: 0,
	            max_key_frame_interval: 1,
	            reservoir_frame_delay: None,
	            low_latency: true,
	            quantizer: 1,
	            min_quantizer: 43,
	            bitrate: 16384,
	            tune: Psychovisual,
	            film_grain_params: None,
	            tile_cols: 0,
	            tile_rows: 0,
	            tiles: 0,
	            speed_settings: SpeedSettings {
	                multiref: false,
	                fast_deblock: true,
	                rdo_lookahead_frames: 10,
	                scene_detection_mode: Standard,
	                cdef: true,
	                lrf: false,
	                lru_on_skip: false,
	                sgr_complexity: Reduced,
	                segmentation: Simple,
	                partition: PartitionSpeedSettings {
	                    encode_bottomup: false,
	                    non_square_partition_max_threshold: BLOCK_8X8,
	                    partition_range: PartitionRange {
	                        min: BLOCK_16X16,
	                        max: BLOCK_32X32,
	                    },
	                },
	                transform: TransformSpeedSettings {
	                    reduced_tx_set: true,
	                    tx_domain_distortion: true,
	                    tx_domain_rate: false,
	                    rdo_tx_decision: false,
	                    enable_inter_tx_split: true,
	                },
	                prediction: PredictionSpeedSettings {
	                    prediction_modes: Simple,
	                    fine_directional_intra: true,
	                },
	                motion: MotionSpeedSettings {
	                    use_satd_subpel: true,
	                    include_near_mvs: false,
	                    me_allow_full_search: false,
	                },
	            },
	        },
	        rate_control: RateControlConfig {
	            emit_pass_data: false,
	            summary: None,
	        },
	        threads: 1,
	        pool: None,
	    },
	    frame_count: 1,
	    pixels: [
	        79,
	        79,
	        81,
	        79,
	        79,
	        255,
	        255,
	        79,
	        79,
	        79,
	    ],
	}

Reproduce with:

	cargo fuzz run encode fuzz/artifacts/encode/crash-6c4a10dc08c47e5e5e818287d7dc742b58548506

Minimize test case with:

	cargo fuzz tmin encode fuzz/artifacts/encode/crash-6c4a10dc08c47e5e5e818287d7dc742b58548506

```

**To Reproduce**
Steps to reproduce the behavior
`cargo fuzz run encode fuzz/artifacts/encode/crash-6c4a10dc08c47e5e5e818287d7dc742b58548506`

**Expected behavior**
No crash

**Required Information**
Toolchain (if is a build problem):
```
cargo 1.72.0-nightly (64fb38c97 2023-05-23)
rustc 1.72.0-nightly (498553fc0 2023-05-29)
NASM version 2.16.01

```
Version:
```
$ rav1e --version
```
Operating system:
```
$ Linux bellini 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Crash artifact:
[crash.zip](https://github.com/xiph/rav1e/files/11600192/crash.zip)

### PR DESCRIPTION
**Pull request by tmatth**
This depends on MAX_TILING_RATE and current dimensions. Fixes #3216

### CODE REVIEW

File: src/api/config/mod.rs [hunk 1]
```diff
@@ -375,6 +383,15 @@ impl Config {
       });
     }
 
+    let max_frame_rate = MAX_TILE_RATE / (config.width * config.height) as f64;
```
Comment (tmatth) [inline src/api/config/mod.rs:386]: My logic might be a little naive here.

File: src/api/config/mod.rs [hunk 2]
```diff
@@ -458,3 +475,21 @@ impl Config {
...
   }
 }
+
+#[cfg(test)]
+mod tests {
+  use crate::tiling::MAX_TILE_RATE;
+  use crate::{Config, EncoderConfig};
+
+  #[test]
+  #[should_panic(expected = "value: InvalidFrameRate")]
```
Comment (tmatth) [inline src/api/config/mod.rs:485]: This is kind of lazy (it'd probably be better to match on the actual type) but I'm not clear on what that would look like.

**Review by barrbrain — APPROVED** [review]
