### PR TITLE
Remove the dimension validation when setting it in the C API

### LINKED ISSUE #2730: capi's check_frame_size() ignores still_picture mode
**Description:**

rav1e is supported in libavif via it's C API (`capi.rs`). When encoding single images (not sequences) with libavif, libavif will engage `still_picture` mode, but despite recent changes to rav1e to allow for images smaller than `16x16` when in `still_picture` mode, the `capi.rs` layer still restricts smaller images even when the `still_picture` flag is set.

**To Reproduce**
Attempt to encode an image smaller than 16x16 (tested with 1x1 and 3x3) with the C API and `still_picture` enabled. The failure path can be seen using libavif's `avifenc`, such as:

    avifenc -c rav1e 1x1.png 1x1.avif

I've verified if I loosen the restriction in `capi.rs`'s `check_frame_size()`, the encode succeeds. The results aren't ideal (see #151), but this ceases to be a failure case.

**Expected behavior**
Enabling `still_picture` via the C API should allow setting `"width"` and `"height"` (also via the C API) to values less than 16. 

Version: v0.4.1
Operating system: All known to work with libavif (Windows, Linux, macOS)

### PR DESCRIPTION
**Pull request by lu-zero**
The configuration is validated already on encoder instantiation.

Fixes #2730

### CODE REVIEW

File: src/capi.rs [hunk 1]
```diff
@@ -623,19 +623,6 @@ fn check_tile_log2(n: Result<usize, ()>) -> Result<usize, ()> {
   }
 }
 
-fn check_frame_size(n: Result<usize, ()>) -> Result<usize, ()> {
```
Comment (rzumer) [inline src/capi.rs:626]: Instead of removing this, you should set the minimum to 1. We still need to make sure that it fits into a u16 and that it's non-zero (and positive).

**Review by rzumer — APPROVED** [review]

**Review by rzumer — APPROVED** [review]
