### PR TITLE
Fix division by zero in CLI output when no inter frame is coded

### LINKED ISSUE #732: Crash when encoding a single frame
```
$ cargo run --bin rav1e --release -- nyan.y4m -o enc_file.y4m -s 3 -l 1
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/rav1e nyan.y4m -o enc_file.ivf -s 3 -l 1`

1280x534 @ 24000/1001 fps
encoded 1/1 frames, 1.00 fps, 68.56 Kb/s, est. size: 0.00 MB                    thread 'main' panicked at 'attempt to divide by zero', src/bin/common.rs:392:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: rav1e::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

### PR DESCRIPTION
**Pull request by rzumer**
Fixes #732.

### CODE REVIEW

File: src/bin/common.rs [hunk 1]
```diff
@@ -389,7 +389,7 @@ impl ProgressInfo {
     Intra Only: {:>6}    avg size: {:>7} B\n\
     Switch:     {:>6}    avg size: {:>7} B",
       key, key_size / key,
-      inter, inter_size / inter,
+      inter, if inter == 0 { 0 } else { inter_size / inter },
```
Comment (lu-zero) [inline src/bin/common.rs]:
```suggestion
      inter, inter_size.checked_div(inter).ok_or(0),
```

Maybe?

or we could directly not print the line?

**Comment by tdaede** [comment]
Did this accidentally pick up other changes?

**Comment by tdaede** [comment]
Oh nvm looks like the sum of all the commits is ok.
