### PR TITLE
Use cc to archive nasm objects

### LINKED ISSUE #2712: nasm fails to find the linker
**Describe the bug**
Build failure on Windows 10 with NASM version 2.15.05 compiled on Aug 28 2020

**To Reproduce**
`cargo install cavif`

**Required Information**
rustc 1.51.0 
rav1e-0.5.0-alpha

**Console Output**

```text
  C:\Users\Nikon the Third\.cargo\registry\src\github.com-1ecc6299db9ec823\rav1e-0.5.0-alpha\src/x86/sse.asm:472: warning: trailing garbage after macro name ignored [-w+other]
  C:\Users\Nikon the Third\.cargo\registry\src\github.com-1ecc6299db9ec823\rav1e-0.5.0-alpha\src/x86/sse.asm:442: ... from macro `WEIGHTED_SSE' defined here
  thread 'main' panicked at 'NASM build failed. Make sure you have nasm installed. https://nasm.us: "failed to spawn process: The system cannot find the file specified. (os error 2)"', C:\Users\Nikon the Third\.cargo\registry\src\github.com-1ecc6299db9ec823\rav1e-0.5.0-alpha\build.rs:120:6
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Originally reported here:

https://github.com/kornelski/cavif-rs/issues/26

### PR DESCRIPTION
**Pull request by kornelski**
Fixes #2712

### CODE REVIEW

**Review by lu-zero — APPROVED** [review]
Looks good to me!

Thank you a lot!

**Comment by lu-zero** [comment]
it needs a rustfmt though ^^;

File: build.rs [hunk 1]
```diff
@@ -112,14 +112,22 @@ fn build_nasm_files() {
...
     config_include_arg.push('/');
-    nasm_rs::compile_library_args(
-      "rav1easm",
-      asm_files,
-      &[&config_include_arg, "-Isrc/"],
-    )
-    .expect(
+    let mut nasm = nasm_rs::Build::new();
+    for file in asm_files {
+        nasm.file(file);
```
Comment (lu-zero) [inline build.rs:117]:
```suggestion
      nasm.file(file);
```

Should make rustfmt happy
