### PR TITLE
Fix inter for 12-bit input.

### LINKED ISSUE #622: decode error at 12 bit caused by 1d697a41fdf7ebb56549cc766a6597228917dac9
bisection reveals 1d697a41fdf7ebb56549cc766a6597228917dac9 introduces a decode desync (though not stream desync) at 12 bit -s3 nyancat (the test run in build.sh, though not run by default).

### PR DESCRIPTION
**Pull request by KyleSiefring**
12-bit is a special case that rounds differently.

See 7.11.3.2. Rounding variable derivation process in the spec.

Fixes #622

### CODE REVIEW

File: src/partition.rs [hunk 1]
```diff
@@ -931,6 +931,12 @@ impl PredictionMode {
         let max_sample_val = ((1 << bit_depth) - 1) as i32;
         let y_filter_idx = if height <= 4 { 4 } else { 0 };
         let x_filter_idx = if width <= 4 { 4 } else { 0 };
+        let (shift_1, shift_2) = {
```
Comment (rzumer) [inline src/partition.rs]: Here you can assign a single variable name for the tuple and access them through `shift.0` and `shift.1`. It might be a bit cleaner.

Comment (KyleSiefring) [reply src/partition.rs]: Done

**Comment by lu-zero** [comment]
Thank you a lot :)
