### PR TITLE
Reject mismatched color configurations

### LINKED ISSUE #2586: Encoder admits invalid color configuration
For example, at `src/header.rs` line 418. If `seq.color_description` is: `ColorPrimaries::BT709`, `TransferCharacteristics::SRGB`, `MatrixCoefficients::Identity`
```rust
assert!(seq.chroma_sampling == ChromaSampling::Cs444);
```
This assertion can fail with an encoder configuration that currently passes validation.

### PR DESCRIPTION
**Pull request by barrbrain**
Fixes #2586. Full pixel range and 4:4:4 subsampling are implied by:
CP_BT_709, TC_SRGB, MC_IDENTITY
<https://aomediacodec.github.io/av1-spec/#color-config-syntax>

### CODE REVIEW

**Comment by barrbrain** [comment]
Se also https://aomediacodec.github.io/av1-spec/#color-config-semantics where it says:

> If matrix_coefficients is equal to MC_IDENTITY, it is a requirement of bitstream conformance that subsampling_x is equal to 0 and subsampling_y is equal to 0.

File: src/api/config/mod.rs [hunk 1]
```diff
@@ -111,6 +111,10 @@ pub enum InvalidConfig {
   /// The configuration
   #[error("Mismatch in the rate control configuration")]
   RateControlConfigurationMismatch,
+
+  /// The rate control needs a target bitrate in order to produce results
```
Comment (lu-zero) [inline src/api/config/mod.rs:115]: the comment seems not matching the error.

**Review by lu-zero — APPROVED** [review]
Looks good to me @kodabb do you agree?
