### PR TITLE
Fix tune psnr

### LINKED ISSUE #1816: "--tune Psnr" mode completely broken
With commit 5bee8ea5f32820a7b25849340dd0116a103074e1,
"--tune Psnr" mode seems completely broken, giving huge coding loss.

[awcy --tune Psnr](https://beta.arewecompressedyet.com/?job=master-5bee8ea5f32820a7b25849340dd0116a103074e1&job=master-5bee8ea5_tune_psnr%402019-10-31T21%3A44%3A50.469Z)

### PR DESCRIPTION
**Pull request by KyleSiefring**
https://beta.arewecompressedyet.com/?job=master-5bee8ea5f32820a7b25849340dd0116a103074e1&job=master-5bee8ea5_tune_psnr%402019-10-31T21%3A44%3A50.469Z&job=fix_tune_psnr%402019-11-02T14%3A08%3A34.004Z

Closes #1816

### CODE REVIEW

File: src/encoder.rs [hunk 1]
```diff
@@ -1220,7 +1220,11 @@ pub fn encode_tx_block<T: Pixel>(
     // Store tx-domain distortion of this block
     tx_dist = coeffs
       .iter()
-      .zip(rcoeffs)
+      .zip(
```
Comment (ycho) [inline src/encoder.rs]: Thanks for fixing this! The 64x64 transformed original source in coeffs is kept w/o zeroing three 32x32 quadrants, but the reconstructed 64x64 rcoeffs (i.e. after dequant + inverse-tx) should have all zeros in those three 32x32 quadrants.
